- name: Apps | Install the latest version of vim and htop
  ansible.builtin.package:
    name:
      - vim
      - htop
      - bat
      - exa
      - finger
    state: latest
  when: ansible_distribution == "Debian"


- name: BAT | Create a directory local/bin
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: '0755'
    force: true
  when: ansible_distribution == "Debian"

# - name: BAT | Configure and link BAT
#   tags: base
#   shell: "ln -s /usr/bin/batcat ~/.local/bin/bat"
#   when: ansible_distribution == "Debian"


- name: BAT | Create a symbolic link for BAT
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: ~/.local/bin/bat
    owner: vagrant
    state: link
    force: true
  when: ansible_distribution == "Debian"